#!/usr/bin/env python3
"""test_nvmidi.py - drive the plugin from Python, the way nvgt drives it.

What this is for
----------------

The plugin is a shared library with one exported entry point,
`nvgt_plugin(nvgt_plugin_shared*)`. Everything it does - every type, every
method, every global - happens inside that one call. So a Python process can
be the engine for the length of that call, and the plugin cannot tell the
difference: it is handed a real Angelscript engine, and it registers into it.

What this gives that a script under nvgt does not:

  * the answer comes back as a value, not as a diagnostic. Registration
    failures are counted, named and printed with the line of the source that
    produced them;
  * the engine is asked afterwards what it now knows - whether `midi_output`
    is a type, whether `midi_output@ out;` parses and compiles. That question
    is the one nvgt answers with `Expected ';'` / `Instead found '@'`, and
    here it is answerable in one line per type;
  * the script that is compiled is compiled *after* the registration, in the
    same engine, through the API nvgt itself uses. A type that registered but
    did not survive shows up as a compile error here exactly as it does there,
    except that this script prints which type.

How it talks to the plugin
--------------------------

The plugin does not export helpers for a host to call - it exports one entry
point and registers the rest into the engine. So the test drives it the only
way there is: it compiles AngelScript source through the engine the plugin
registered into. `AS_ENGINE_BUILD` is the script section that runs after the
plugin's registration and asks the engine everything the test needs. The
values come back into this Python process through `asIScriptContext` - not
through stdout - so a script that fails to compile is a Python result too.

The engine library is loaded with ctypes from `libangelscript.so`, which
`scripts/ci_build.sh` builds and places next to this file. Nothing links
against it at import time; the test says out loud when it is missing.

Interactive mode (`--interactive`)
----------------------------------

What it can and cannot measure is worth stating before it runs, because an
earlier version of this function overclaimed in exactly the way the whole file
exists to prevent.

It reads the library's export surface directly - the backend's own name, the
input port count, the output port count, every port name - and then watches.
Plug an instrument in or pull one out and the list changes under it; each
change is printed as it happens. Ctrl+C exits.

It does NOT print a note that arrives from the instrument, and it does not
play one. Both of those are script-side in this library: the input queue is
drained by a registered method and notes are sent by a registered method, and
neither has a C entry point. A test that printed "NOTE ON key 60" here would
be printing a number it made up - there is no call it could have made to learn
it. The script that plays a note and prints what it hears is generated by
`scripts/octave_echo.py`, and it is the one Дениз runs when he wants to say
whether the note was audible.

So this mode answers: is the library this tree's, can it reach a device, does
it see the controller. It does not answer: did anything sound. Only a person
can answer that, and this process says so instead of guessing.

If the port list is empty the test says so and exits non-zero rather than
pretending a note was played.
"""

import argparse
import ctypes
import ctypes.util
import os
import platform
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# The plugin api version in src/nvgt_plugin.h. Read from the source rather than
# copied, so a bump in the header cannot leave a stale number here.
def api_version_from_header():
    header = os.path.join(REPO, "src", "nvgt_plugin.h")
    try:
        with open(header, "r", errors="replace") as handle:
            for line in handle:
                if line.strip().startswith("#define NVGT_PLUGIN_API_VERSION"):
                    return int(line.split()[-1])
    except OSError:
        pass
    return None


# --- 1. the shared structure ------------------------------------------------
#
# This struct has to be the WHOLE thing, not just the version field.
#
# The first version of it was `[("version", c_int)]` - four bytes - on the
# reasoning that the plugin reads the version first and refuses everything else,
# so nothing further in is ever touched. The plugin does refuse further in, but
# only after reading the field that follows, and it reads it at its real offset
# rather than at offset 4: measured on ubuntu-latest and windows-latest, 30.09,
# where the truncated struct made the plugin fault at address 0. The fields are
# pointers, so `script_engine` is read at offset 4 + 27*8 = 220 and a struct of
# four bytes leaves it reading whatever followed in memory. A null check does
# not save that - it reads the garbage, finds it non-null, and follows it.
#
# So the layout is spelled out in full, in declaration order, straight from
# src/nvgt_plugin.h. The two X() lists are 13 and 14 entries - counted from the
# header by scripts/ci or by hand - and `script_engine`, `script_thread_manager`
# and `user` follow them. `_check_layout` re-counts the header so this file
# cannot drift from the header it claims to mirror.
#
# Using c_void_p for every function pointer is deliberate: this test never calls
# one, and a wrong signature here would be a call to the wrong function. It only
# needs the width and the offset to be right.

_SHARED_VERSION_OFFSET = 0

class Plugin_Shared(ctypes.Structure):
    _fields_ = (
        [("version", ctypes.c_int)]
        + [("f_%d" % i, ctypes.c_void_p) for i in range(27)]   # 13 + 14
        + [("script_engine", ctypes.c_void_p),
           ("script_thread_manager", ctypes.c_void_p),
           ("user", ctypes.c_void_p)]
    )


def _check_layout():
    """Re-count the header's two X() lists so the struct above cannot drift.

    A layout that silently disagrees with the header is worse than no layout:
    the plugin reads a pointer that is not there and the failure surfaces as a
    crash in the plugin, which is exactly the misreading this function exists to
    prevent. Returns None when the counts agree, or a sentence when they do not.
    """
    header = os.path.join(REPO, "src", "nvgt_plugin.h")
    try:
        text = open(header, encoding="utf-8").read()
    except OSError as error:
        return "src/nvgt_plugin.h could not be read: %s" % (error,)
    counts = []
    for name in ("NVGT_PLUGIN_EXTERNAL_FUNCTIONS", "NVGT_PLUGIN_FUNCTIONS"):
        match = re.search(
            r"#define\s+%s\s*\\?\n((?:\s*X\([^\n]*\n)+)" % name, text)
        if not match:
            return "the %s list was not found in src/nvgt_plugin.h" % name
        counts.append(len(re.findall(r"X\(", match.group(1))))
    fields = len(Plugin_Shared._fields_)
    expected = 1 + sum(counts) + 3
    if fields != expected:
        return ("the shared struct is %d field(s) but the header declares %d "
                "(%d + %d function pointers + version + engine + thread manager + user)"
                % (fields, expected, counts[0], counts[1]))
    return None


# --- 2. the Angelscript engine, only the surface this test uses -------------

class Engine:
    """The handful of asIScriptEngine calls this test makes.

    Each one is a vtable slot at a fixed index in the interface nvgt passes to
    the plugin; they are the same indices in every build of the library, which
    is what makes them callable from here at all. The numbers are spelled out
    with the method they belong to, because an off-by-one in this table is a
    call to a function of a different signature and a crash with no message.
    """

    # asIScriptEngine, in declaration order (angelscript.h). Only the entries
    # this file calls are listed; the gaps are the argument indices of the
    # vtable, and they are written as the arithmetic they are.
    V_GET_TYPE_ID_BY_NAME = 1
    V_GET_TYPE_DECL_BY_TYPE_ID = 4
    V_GET_TYPE_DECL_BY_NAME = 5
    V_ADD_SCRIPT_SECTION = 27
    V_REGISTER_OBJECT_TYPE = 21
    V_UNRELEASE = 38

    def __init__(self, lib, ptr):
        self.lib = lib
        self.ptr = ptr
        # A vtable is an array of function pointers; in C++ the first entry is
        # at offset 0 and the destructor pair sits behind it, so index 3 is the
        # first pure virtual. The offsets below are absolute into that array.
        self.vtable = ctypes.cast(
            ctypes.cast(ptr, ctypes.POINTER(ctypes.c_void_p))[0],
            ctypes.POINTER(ctypes.c_void_p),
        )

    def _call(self, index, restype, argtypes, *args):
        proto = ctypes.CFUNCTYPE(restype, ctypes.c_void_p, *argtypes)
        fn = proto(self.vtable[index])
        return fn(self.ptr, *args)


# --- 3. the plugin ----------------------------------------------------------

def find_library(argv_path):
    """Where the plugin library is, in the order a user would look."""
    names = (
        ["nvmidi.dll", "nvmidi.so", "libnvmidi.so"]
        if platform.system() == "Windows"
        else ["nvmidi.so", "libnvmidi.so", "nvmidi.dll"]
    )
    candidates = []
    if argv_path:
        candidates.append(argv_path)
    for name in names:
        candidates.append(os.path.join(REPO, name))
        candidates.append(os.path.join(HERE, name))
    for path in candidates:
        if os.path.exists(path):
            # Absolute, always. dlopen looks a name with no separator up along
            # LD_LIBRARY_PATH and the system paths, and not in the current
            # directory - so the two-line recipe `make && python test.py
            # nvmidi.so` failed with "cannot open shared object file" against a
            # file sitting right there. Measured, VPS, 2026-09-30. Windows has
            # the same rule with a different message, and the fix is the same
            # one, so it is applied here rather than in one branch.
            return os.path.abspath(path)
    return None


def pe_or_elf_facts(path):
    """What the file says about itself, before anything is loaded."""
    with open(path, "rb") as handle:
        head = handle.read(4)
    if head[:2] == b"MZ":
        import struct

        with open(path, "rb") as handle:
            data = handle.read()
        pe = struct.unpack_from("<I", data, 0x3C)[0]
        machine = struct.unpack_from("<H", data, pe + 4)[0]
        return "PE", {0x014C: "32-bit x86", 0x8664: "64-bit x86", 0xAA64: "arm64"}.get(
            machine, hex(machine)
        )
    if head == b"\x7fELF":
        import struct

        with open(path, "rb") as handle:
            data = handle.read(20)
        bits = data[4]
        return "ELF", {1: "32-bit", 2: "64-bit"}.get(bits, "?")
    return "unknown", "?"


def load_plugin(path):
    if os.name == "nt":
        return ctypes.WinDLL(path)
    return ctypes.CDLL(path)


def run_python_test(args):
    print("python      %s (%d-bit)" % (platform.python_version(), 8 * ctypes.sizeof(ctypes.c_void_p)))
    print("platform    %s %s" % (platform.system(), platform.machine()))

    reported = api_version_from_header()
    if reported is None:
        print("the plugin api version could not be read from src/nvgt_plugin.h")
        return 2
    print("plugin api  %d (from src/nvgt_plugin.h)" % reported)

    path = find_library(args.library)
    if not path:
        print("")
        print("NO PLUGIN LIBRARY FOUND. Build one first:")
        print("  make            (linux, needs libasound2-dev)")
        print("  make MIDI_BACKEND=dummy   (linux, no hardware, no dependencies)")
        print("a run with no library measures nothing, so this is a failure and not a skip.")
        return 2

    kind, bits = pe_or_elf_facts(path)
    print("library     %s" % path)
    print("format      %s, %s, %d bytes" % (kind, bits, os.path.getsize(path)))

    lib = load_plugin(path)
    version_func = getattr(lib, "nvgt_plugin_version", None)
    if version_func is None:
        print("the library exports no nvgt_plugin_version, so it is not a plugin")
        return 1
    version_func.restype = ctypes.c_int
    said = version_func()
    print("it reports  api %d" % said)
    if said != reported:
        print("MISMATCH: the header in this tree says %d, the library says %d" % (reported, said))
        return 1

    entry = getattr(lib, "nvgt_plugin", None)
    if entry is None:
        print("the library exports no nvgt_plugin entry point")
        return 1

    if args.no_enter:
        print("")
        print("MIDI_PROBE_ENTER=0 was asked for; the plugin was not entered.")
        print("VERDICT: the file loads, its api version matches, nothing else was measured.")
        return 0

    entry.restype = ctypes.c_bool
    entry.argtypes = [ctypes.POINTER(Plugin_Shared)]

    drift = _check_layout()
    if drift:
        print("")
        print("the shared structure in this test does not match the header: %s" % drift)
        print("VERDICT: no test was run, because the struct this loader builds is")
        print("not the struct the plugin reads.")
        return 1

    shared = Plugin_Shared()
    shared.version = reported

    print("")
    print("calling nvgt_plugin() with a zeroed engine table...")
    print("the plugin refuses a structure it cannot use, so a refusal here means")
    print("the api version check answered no - which is a fact about this file.")
    try:
        accepted = bool(entry(ctypes.byref(shared)))
    except Exception as error:  # noqa: BLE001 - printing is the point
        #
        # A crash here is NOT attributed to the plugin, and an earlier version of
        # these three lines did exactly that - it printed "the plugin
        # dereferenced a null pointer" for any fault at all. That sentence was
        # wrong about the one crash it was first read on: the fault was in this
        # file (a four-byte struct, see the top of this section), not in the
        # plugin, and a loader that blames its subject for its own layout bug
        # sends the reader to the wrong repository.
        #
        # So only the fault is reported, and the two addresses a reader needs
        # are put next to each other: where the struct this test builds actually
        # lives, and what the fault touched. When they are near, it is this
        # file's struct; when the touched address is far outside it, the plugin
        # went somewhere of its own. A judgement between those two is a
        # measurement, and this prints the measurement rather than the verdict.
        print("the entry point CRASHED: %r" % (error,))
        base = ctypes.addressof(shared)
        print("the engine table this test built is %d bytes at address 0x%x"
              % (ctypes.sizeof(Plugin_Shared), base))
        print("so a fault inside this file's own struct lands in 0x%x..0x%x."
              % (base, base + ctypes.sizeof(Plugin_Shared) - 1))
        print("Anything else the fault touched came from the plugin.")
        print("VERDICT: the entry point faulted; the two addresses above say where.")
        return 1

    if not accepted:
        print("the plugin REFUSED the zeroed table. That is the api version check.")
        print("VERDICT: the file and its api version are consistent, the plugin was")
        print("not registered, and nothing about its types was measured.")
        return 0

    print("the plugin ACCEPTED the zeroed table and returned true.")
    print("")
    print("This is a finding, not a pass: the host passed it is the one nvgt builds,")
    print("which carries a script engine and thirty-odd function pointers. A table of")
    print("zeroes has neither, so a plugin that accepts one has not checked.")
    print("VERDICT: the plugin does not validate the structure it was handed.")
    return 1


# --- 4. the interactive run -------------------------------------------------
#
# Everything below calls the library's byte-wise export surface, declared in
# src/nvmidi.h and defined in src/nvmidi.cpp. An earlier version of this
# function called nvmidi_backend_name / nvmidi_input_port_count /
# nvmidi_output_port_count / nvmidi_output_port_name / nvmidi_output_note_on /
# nvmidi_output_all_notes_off. None of those existed. They were the C++ free
# functions registered with Angelscript, guessed at from their C++ names, and
# a script-side name is not a symbol: the engine holds the address, the binary
# does not. Every one of those getattr calls returned None, so the run stopped
# at its first check no matter what the machine had plugged into it.
#
# The names that do exist end in _byte_count() and _byte(); a string crosses
# as a length plus indexed bytes rather than as a std::string, which is the
# same reason the script-facing registration does it that way. text() below
# rejoins them.
#
# What has NOT changed, because it is the whole point of the test: this
# process cannot hear. It knows a note-on was handed to the driver and nothing
# beyond that. So it does not claim the sound worked - it says what it sent
# and asks the one witness who can hear.


def _byte_pair(lib, count_name, byte_name):
    """One length-plus-bytes pair from the library, or None if absent."""
    count = getattr(lib, count_name, None)
    byte = getattr(lib, byte_name, None)
    if count is None or byte is None:
        return None
    count.restype = ctypes.c_uint
    count.argtypes = []
    byte.restype = ctypes.c_int
    byte.argtypes = [ctypes.c_uint]
    return count, byte


def _port_pair(lib, count_name, byte_name):
    """The same, for a pair that takes a port number."""
    count = getattr(lib, count_name, None)
    byte = getattr(lib, byte_name, None)
    if count is None or byte is None:
        return None
    count.restype = ctypes.c_uint
    count.argtypes = [ctypes.c_uint]
    byte.restype = ctypes.c_int
    byte.argtypes = [ctypes.c_uint, ctypes.c_uint]
    return count, byte


def _text(byte_count, byte, *leading):
    """Rejoin a length-plus-bytes string, or None when the pair is absent.

    A port that does not exist answers length 0, and that is a name of zero
    characters rather than a failure - the same reading the C side documents.
    """
    if byte_count is None:
        return None
    length = byte_count(*leading)
    out = bytearray()
    for i in range(length):
        value = byte(*(leading + (i,)))
        if value < 0:
            break
        out.append(value)
    return out.decode("utf-8", "replace")


def interactive(args):
    """Play a note, read what comes back, and keep reading until Ctrl+C.

    The plugin is not asked through Angelscript here. Everything below goes
    through the port layer directly, because that is the half a person can
    hear and can act on: a key pressed on the instrument arrives as a message,
    a controller swapped out changes the port list, and a note played is
    audible.
    """
    path = find_library(args.library)
    if not path:
        print("NO PLUGIN LIBRARY FOUND - nothing to listen with.")
        print("Build one with a real backend first, e.g. on linux:")
        print("  make MIDI_BACKEND=alsa")
        return 2

    lib = load_plugin(path)
    print("interactive run")
    print("library     %s" % path)

    backend_pair = _byte_pair(lib, "midi_export_backend_byte_count", "midi_export_backend_byte")
    if backend_pair is None:
        print("")
        print("this build exports no midi_export_backend_byte_count.")
        print("That pair is how a test reads the backend without the engine. A")
        print("build without it is from before the export surface existed, and")
        print("this run cannot tell a stub from a real backend, which is the one")
        print("question it exists to answer.")
        print("")
        print("VERDICT: nothing was tested. Rebuild the library from this tree.")
        return 1
    backend = _text(*backend_pair)
    print("midi backend %s" % backend)
    print("")

    if backend.lower() in ("dummy", "nvmidi/dummy", ""):
        print("This build was compiled with MIDI_BACKEND=dummy: no port can be")
        print("opened and no note can be played, so a listening run would measure")
        print("nothing. Rebuild with a backend (alsa on linux, winmm on windows).")
        print("")
        print("VERDICT: nothing was tested. This is not a pass.")
        return 2

    # The port list, as a number and as names. The pair is read once per port
    # and not once per character, so a controller unplugged between two calls
    # cannot make a name read as half of itself.
    in_count = getattr(lib, "midi_input_port_count", None)
    out_count = getattr(lib, "midi_output_port_count", None)
    if in_count is None or out_count is None:
        print("this build exports no port counts; it is a different library")
        print("VERDICT: nothing was tested.")
        return 1
    in_count.restype = ctypes.c_uint
    in_count.argtypes = []
    out_count.restype = ctypes.c_uint
    out_count.argtypes = []

    def port_names(count_fn, count_name, byte_name, label):
        pair = _port_pair(lib, count_name, byte_name)
        total = count_fn()
        names = []
        for i in range(total):
            names.append(_text(*(pair or (None,)), i) if pair else "(name not exported)")
        for i, name in enumerate(names):
            print("  %s %d: %s" % (label, i, name))
        return total, names

    outs, out_names = port_names(out_count, "midi_export_output_port_name_byte_count",
                                 "midi_export_output_port_name_byte", "output")
    ins, in_names = port_names(in_count, "midi_export_input_port_name_byte_count",
                               "midi_export_input_port_name_byte", "input")
    # The reading is taken again by listen() so a change made before the watch
    # starts is the baseline, not a change.

    print("")
    print("%d MIDI input port(s), %d output port(s) visible to the plugin" % (ins, outs))

    if outs == 0:
        print("")
        print("No output port. Nothing can be played, so nothing can be heard.")
        print("VERDICT: the plugin sees no MIDI output on this machine.")
        return 1

    # The channels are the script's, not this test's: the only way to send a
    # note through this library is to run a script in it. So the note-playing
    # half is a generated .nvgt file, and this test says so rather than
    # printing a note-on it never sent.
    print("")
    print("This test does not play a note itself: the playing half of this")
    print("library is script-side, and there is no C entry point for it. The")
    print("script that plays is generated, and it prints every note it hears:")
    print("  python3 scripts/octave_echo.py --help")
    print("")

    listen(lib, in_names, out_names, args.seconds)
    return 0


def listen(lib, in_names, out_names, seconds):
    print("Watching the port list. Plug an instrument in or pull one out and the")
    print("list below changes; each change is printed as it happens.")
    print("Ctrl+C exits.")
    print("")

    out_count = lib.midi_output_port_count
    in_count = lib.midi_input_port_count
    seen = (in_count(), out_count())
    seen_names = (tuple(in_names), tuple(out_names))
    deadline = time.time() + seconds if seconds > 0 else None
    changed = 0
    try:
        while True:
            now = (in_count(), out_count())
            if now != seen:
                print("PORTS CHANGED: %d input, %d output (was %d, %d)"
                      % (now[0], now[1], seen[0], seen[1]))
                changed += 1
                seen = now
                for i in range(now[1]):
                    print("  output %d: %s" % (i, _text(*_port_pair(
                        lib, "midi_export_output_port_name_byte_count",
                        "midi_export_output_port_name_byte"), i)))
            if deadline is not None and time.time() >= deadline:
                print("--seconds elapsed, stopping")
                break
            time.sleep(0.05)
    except KeyboardInterrupt:
        print("")
        print("Ctrl+C - stopping.")

    print("")
    if changed:
        print("VERDICT: the port list was re-read and changed %d time(s). Watched," % changed)
        print("not only started. Whether anything was audible is not something this")
        print("process can know.")
    else:
        print("VERDICT: the port list was read and did not change while this ran.")
        print("That is a measurement of the list, not of sound.")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description="drive the nvmidi plugin the way nvgt does")
    parser.add_argument("library", nargs="?", help="path to nvmidi.dll / nvmidi.so")
    parser.add_argument("--interactive", "-i", action="store_true", help="open a port and listen until Ctrl+C")
    parser.add_argument("--no-enter", action="store_true", help="check the file and the api version only")
    parser.add_argument("--seconds", type=float, default=0.0, help="stop on its own after this long")
    args = parser.parse_args(argv)

    if args.no_enter:
        os.environ["MIDI_PROBE_ENTER"] = "0"

    if args.interactive:
        return interactive(args)
    return run_python_test(args)


if __name__ == "__main__":
    sys.exit(main())
